// Code generated by ent, DO NOT EDIT.

package storefront

import (
	"ant/ent/schema"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the storefront type in the database.
	Label = "storefront"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldDivisionID holds the string denoting the division_id field in the database.
	FieldDivisionID = "division_id"
	// FieldHeroImage holds the string denoting the hero_image field in the database.
	FieldHeroImage = "hero_image"
	// FieldAssessments holds the string denoting the assessments field in the database.
	FieldAssessments = "assessments"
	// FieldGallery holds the string denoting the gallery field in the database.
	FieldGallery = "gallery"
	// FieldFoodTags holds the string denoting the food_tags field in the database.
	FieldFoodTags = "food_tags"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the storefront in the database.
	Table = "ant_storefront"
)

// Columns holds all SQL columns for storefront fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAppID,
	FieldDivisionID,
	FieldHeroImage,
	FieldAssessments,
	FieldGallery,
	FieldFoodTags,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultAssessments holds the default value on creation for the "assessments" field.
	DefaultAssessments []schema.Assessment
	// DefaultGallery holds the default value on creation for the "gallery" field.
	DefaultGallery []schema.GalleryImage
	// DefaultFoodTags holds the default value on creation for the "food_tags" field.
	DefaultFoodTags []schema.FoodTag
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int8
)

// OrderOption defines the ordering options for the Storefront queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAppID orders the results by the app_id field.
func ByAppID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppID, opts...).ToFunc()
}

// ByDivisionID orders the results by the division_id field.
func ByDivisionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDivisionID, opts...).ToFunc()
}

// ByHeroImage orders the results by the hero_image field.
func ByHeroImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeroImage, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}
