// Code generated by ent, DO NOT EDIT.

package ordergroup

import (
	"ant/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEQ(FieldAppID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEQ(FieldUserID, v))
}

// DivisionID applies equality check predicate on the "division_id" field. It's identical to DivisionIDEQ.
func DivisionID(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEQ(FieldDivisionID, v))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEQ(FieldToken, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int8) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLTE(FieldUpdatedAt, v))
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEQ(FieldAppID, v))
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNEQ(FieldAppID, v))
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldIn(FieldAppID, vs...))
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNotIn(FieldAppID, vs...))
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGT(FieldAppID, v))
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGTE(FieldAppID, v))
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLT(FieldAppID, v))
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLTE(FieldAppID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLTE(FieldUserID, v))
}

// DivisionIDEQ applies the EQ predicate on the "division_id" field.
func DivisionIDEQ(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEQ(FieldDivisionID, v))
}

// DivisionIDNEQ applies the NEQ predicate on the "division_id" field.
func DivisionIDNEQ(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNEQ(FieldDivisionID, v))
}

// DivisionIDIn applies the In predicate on the "division_id" field.
func DivisionIDIn(vs ...int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldIn(FieldDivisionID, vs...))
}

// DivisionIDNotIn applies the NotIn predicate on the "division_id" field.
func DivisionIDNotIn(vs ...int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNotIn(FieldDivisionID, vs...))
}

// DivisionIDGT applies the GT predicate on the "division_id" field.
func DivisionIDGT(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGT(FieldDivisionID, v))
}

// DivisionIDGTE applies the GTE predicate on the "division_id" field.
func DivisionIDGTE(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGTE(FieldDivisionID, v))
}

// DivisionIDLT applies the LT predicate on the "division_id" field.
func DivisionIDLT(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLT(FieldDivisionID, v))
}

// DivisionIDLTE applies the LTE predicate on the "division_id" field.
func DivisionIDLTE(v int) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLTE(FieldDivisionID, v))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldContainsFold(FieldToken, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelIsNil applies the IsNil predicate on the "label" field.
func LabelIsNil() predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldIsNull(FieldLabel))
}

// LabelNotNil applies the NotNil predicate on the "label" field.
func LabelNotNil() predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNotNull(FieldLabel))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldContainsFold(FieldLabel, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int8) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int8) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int8) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int8) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int8) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int8) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int8) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int8) predicate.OrderGroup {
	return predicate.OrderGroup(sql.FieldLTE(FieldStatus, v))
}

// HasOrders applies the HasEdge predicate on the "orders" edge.
func HasOrders() predicate.OrderGroup {
	return predicate.OrderGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrdersWith applies the HasEdge predicate on the "orders" edge with a given conditions (other predicates).
func HasOrdersWith(preds ...predicate.Order) predicate.OrderGroup {
	return predicate.OrderGroup(func(s *sql.Selector) {
		step := newOrdersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OrderGroup) predicate.OrderGroup {
	return predicate.OrderGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OrderGroup) predicate.OrderGroup {
	return predicate.OrderGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OrderGroup) predicate.OrderGroup {
	return predicate.OrderGroup(sql.NotPredicates(p))
}
