// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AntOrderColumns holds the columns for the "ant_order" table.
	AntOrderColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "app_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeInt8, Default: 1},
	}
	// AntOrderTable holds the schema information for the "ant_order" table.
	AntOrderTable = &schema.Table{
		Name:       "ant_order",
		Columns:    AntOrderColumns,
		PrimaryKey: []*schema.Column{AntOrderColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "order_app_id",
				Unique:  false,
				Columns: []*schema.Column{AntOrderColumns[3]},
			},
		},
	}
	// AntProductColumns holds the columns for the "ant_product" table.
	AntProductColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "app_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeInt8, Default: 1},
	}
	// AntProductTable holds the schema information for the "ant_product" table.
	AntProductTable = &schema.Table{
		Name:       "ant_product",
		Columns:    AntProductColumns,
		PrimaryKey: []*schema.Column{AntProductColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "product_app_id",
				Unique:  false,
				Columns: []*schema.Column{AntProductColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AntOrderTable,
		AntProductTable,
	}
)

func init() {
	AntOrderTable.Annotation = &entsql.Annotation{
		Table: "ant_order",
	}
	AntProductTable.Annotation = &entsql.Annotation{
		Table: "ant_product",
	}
}
