// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AntAttributeColumns holds the columns for the "ant_attribute" table.
	AntAttributeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "app_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeInt8, Default: 1},
	}
	// AntAttributeTable holds the schema information for the "ant_attribute" table.
	AntAttributeTable = &schema.Table{
		Name:       "ant_attribute",
		Columns:    AntAttributeColumns,
		PrimaryKey: []*schema.Column{AntAttributeColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "attribute_app_id",
				Unique:  false,
				Columns: []*schema.Column{AntAttributeColumns[3]},
			},
		},
	}
	// AntAttributeOptionColumns holds the columns for the "ant_attribute_option" table.
	AntAttributeOptionColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "value", Type: field.TypeString},
		{Name: "attribute_id", Type: field.TypeInt},
	}
	// AntAttributeOptionTable holds the schema information for the "ant_attribute_option" table.
	AntAttributeOptionTable = &schema.Table{
		Name:       "ant_attribute_option",
		Columns:    AntAttributeOptionColumns,
		PrimaryKey: []*schema.Column{AntAttributeOptionColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ant_attribute_option_ant_attribute_options",
				Columns:    []*schema.Column{AntAttributeOptionColumns[4]},
				RefColumns: []*schema.Column{AntAttributeColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "attributeoption_attribute_id",
				Unique:  false,
				Columns: []*schema.Column{AntAttributeOptionColumns[4]},
			},
		},
	}
	// AntOrderColumns holds the columns for the "ant_order" table.
	AntOrderColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "app_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "division_id", Type: field.TypeInt},
		{Name: "customer_name", Type: field.TypeString},
		{Name: "customer_contact", Type: field.TypeString},
		{Name: "ordered_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeInt8, Default: 1},
		{Name: "tax_percent", Type: field.TypeFloat64, Default: 0},
		{Name: "ip_address", Type: field.TypeString, Nullable: true, Size: 45},
		{Name: "device_id", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "group_id", Type: field.TypeInt},
	}
	// AntOrderTable holds the schema information for the "ant_order" table.
	AntOrderTable = &schema.Table{
		Name:       "ant_order",
		Columns:    AntOrderColumns,
		PrimaryKey: []*schema.Column{AntOrderColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ant_order_ant_order_group_orders",
				Columns:    []*schema.Column{AntOrderColumns[13]},
				RefColumns: []*schema.Column{AntOrderGroupColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "order_app_id_status",
				Unique:  false,
				Columns: []*schema.Column{AntOrderColumns[3], AntOrderColumns[9]},
			},
			{
				Name:    "order_group_id",
				Unique:  false,
				Columns: []*schema.Column{AntOrderColumns[13]},
			},
			{
				Name:    "order_app_id_division_id_device_id",
				Unique:  false,
				Columns: []*schema.Column{AntOrderColumns[3], AntOrderColumns[5], AntOrderColumns[12]},
			},
		},
	}
	// AntOrderGroupColumns holds the columns for the "ant_order_group" table.
	AntOrderGroupColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "app_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "division_id", Type: field.TypeInt},
		{Name: "token", Type: field.TypeString},
		{Name: "label", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeInt8, Default: 1},
	}
	// AntOrderGroupTable holds the schema information for the "ant_order_group" table.
	AntOrderGroupTable = &schema.Table{
		Name:       "ant_order_group",
		Columns:    AntOrderGroupColumns,
		PrimaryKey: []*schema.Column{AntOrderGroupColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ordergroup_app_id_token",
				Unique:  true,
				Columns: []*schema.Column{AntOrderGroupColumns[3], AntOrderGroupColumns[6]},
			},
			{
				Name:    "ordergroup_app_id_status",
				Unique:  false,
				Columns: []*schema.Column{AntOrderGroupColumns[3], AntOrderGroupColumns[8]},
			},
		},
	}
	// AntOrderProductColumns holds the columns for the "ant_order_product" table.
	AntOrderProductColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "product_id", Type: field.TypeInt},
		{Name: "product_name", Type: field.TypeString},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "quantity", Type: field.TypeInt},
		{Name: "attributes", Type: field.TypeJSON},
		{Name: "order_id", Type: field.TypeInt},
	}
	// AntOrderProductTable holds the schema information for the "ant_order_product" table.
	AntOrderProductTable = &schema.Table{
		Name:       "ant_order_product",
		Columns:    AntOrderProductColumns,
		PrimaryKey: []*schema.Column{AntOrderProductColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ant_order_product_ant_order_products",
				Columns:    []*schema.Column{AntOrderProductColumns[8]},
				RefColumns: []*schema.Column{AntOrderColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "orderproduct_order_id",
				Unique:  false,
				Columns: []*schema.Column{AntOrderProductColumns[8]},
			},
			{
				Name:    "orderproduct_product_id",
				Unique:  false,
				Columns: []*schema.Column{AntOrderProductColumns[3]},
			},
		},
	}
	// AntProductColumns holds the columns for the "ant_product" table.
	AntProductColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "app_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
		{Name: "price", Type: field.TypeFloat64, Default: 0},
		{Name: "status", Type: field.TypeInt8, Default: 1},
	}
	// AntProductTable holds the schema information for the "ant_product" table.
	AntProductTable = &schema.Table{
		Name:       "ant_product",
		Columns:    AntProductColumns,
		PrimaryKey: []*schema.Column{AntProductColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "product_app_id",
				Unique:  false,
				Columns: []*schema.Column{AntProductColumns[3]},
			},
		},
	}
	// AntProductAttributeColumns holds the columns for the "ant_product_attribute" table.
	AntProductAttributeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "is_mandatory", Type: field.TypeBool, Default: false},
		{Name: "options", Type: field.TypeJSON},
		{Name: "attribute_id", Type: field.TypeInt},
		{Name: "product_id", Type: field.TypeInt},
	}
	// AntProductAttributeTable holds the schema information for the "ant_product_attribute" table.
	AntProductAttributeTable = &schema.Table{
		Name:       "ant_product_attribute",
		Columns:    AntProductAttributeColumns,
		PrimaryKey: []*schema.Column{AntProductAttributeColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ant_product_attribute_ant_attribute_product_attributes",
				Columns:    []*schema.Column{AntProductAttributeColumns[5]},
				RefColumns: []*schema.Column{AntAttributeColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "ant_product_attribute_ant_product_attributes",
				Columns:    []*schema.Column{AntProductAttributeColumns[6]},
				RefColumns: []*schema.Column{AntProductColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "productattribute_product_id_attribute_id",
				Unique:  true,
				Columns: []*schema.Column{AntProductAttributeColumns[6], AntProductAttributeColumns[5]},
			},
			{
				Name:    "productattribute_attribute_id",
				Unique:  false,
				Columns: []*schema.Column{AntProductAttributeColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AntAttributeTable,
		AntAttributeOptionTable,
		AntOrderTable,
		AntOrderGroupTable,
		AntOrderProductTable,
		AntProductTable,
		AntProductAttributeTable,
	}
)

func init() {
	AntAttributeTable.Annotation = &entsql.Annotation{
		Table: "ant_attribute",
	}
	AntAttributeOptionTable.ForeignKeys[0].RefTable = AntAttributeTable
	AntAttributeOptionTable.Annotation = &entsql.Annotation{
		Table: "ant_attribute_option",
	}
	AntOrderTable.ForeignKeys[0].RefTable = AntOrderGroupTable
	AntOrderTable.Annotation = &entsql.Annotation{
		Table: "ant_order",
	}
	AntOrderGroupTable.Annotation = &entsql.Annotation{
		Table: "ant_order_group",
	}
	AntOrderProductTable.ForeignKeys[0].RefTable = AntOrderTable
	AntOrderProductTable.Annotation = &entsql.Annotation{
		Table: "ant_order_product",
	}
	AntProductTable.Annotation = &entsql.Annotation{
		Table: "ant_product",
	}
	AntProductAttributeTable.ForeignKeys[0].RefTable = AntAttributeTable
	AntProductAttributeTable.ForeignKeys[1].RefTable = AntProductTable
	AntProductAttributeTable.Annotation = &entsql.Annotation{
		Table: "ant_product_attribute",
	}
}
