// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ant/ent/attribute"
	"ant/ent/attributeoption"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AttributeOption is the model entity for the AttributeOption schema.
type AttributeOption struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AttributeID holds the value of the "attribute_id" field.
	AttributeID int `json:"attribute_id,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AttributeOptionQuery when eager-loading is set.
	Edges        AttributeOptionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AttributeOptionEdges holds the relations/edges for other nodes in the graph.
type AttributeOptionEdges struct {
	// Attribute holds the value of the attribute edge.
	Attribute *Attribute `json:"attribute,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AttributeOrErr returns the Attribute value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AttributeOptionEdges) AttributeOrErr() (*Attribute, error) {
	if e.Attribute != nil {
		return e.Attribute, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: attribute.Label}
	}
	return nil, &NotLoadedError{edge: "attribute"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AttributeOption) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case attributeoption.FieldID, attributeoption.FieldAttributeID:
			values[i] = new(sql.NullInt64)
		case attributeoption.FieldValue:
			values[i] = new(sql.NullString)
		case attributeoption.FieldCreatedAt, attributeoption.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AttributeOption fields.
func (_m *AttributeOption) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case attributeoption.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case attributeoption.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case attributeoption.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case attributeoption.FieldAttributeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attribute_id", values[i])
			} else if value.Valid {
				_m.AttributeID = int(value.Int64)
			}
		case attributeoption.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the AttributeOption.
// This includes values selected through modifiers, order, etc.
func (_m *AttributeOption) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAttribute queries the "attribute" edge of the AttributeOption entity.
func (_m *AttributeOption) QueryAttribute() *AttributeQuery {
	return NewAttributeOptionClient(_m.config).QueryAttribute(_m)
}

// Update returns a builder for updating this AttributeOption.
// Note that you need to call AttributeOption.Unwrap() before calling this method if this AttributeOption
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AttributeOption) Update() *AttributeOptionUpdateOne {
	return NewAttributeOptionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AttributeOption entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AttributeOption) Unwrap() *AttributeOption {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AttributeOption is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AttributeOption) String() string {
	var builder strings.Builder
	builder.WriteString("AttributeOption(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("attribute_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttributeID))
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(_m.Value)
	builder.WriteByte(')')
	return builder.String()
}

// AttributeOptions is a parsable slice of AttributeOption.
type AttributeOptions []*AttributeOption
