// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ant/ent/attribute"
	"ant/ent/attributeoption"
	"ant/ent/predicate"
	"ant/ent/productattribute"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AttributeUpdate is the builder for updating Attribute entities.
type AttributeUpdate struct {
	config
	hooks    []Hook
	mutation *AttributeMutation
}

// Where appends a list predicates to the AttributeUpdate builder.
func (_u *AttributeUpdate) Where(ps ...predicate.Attribute) *AttributeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AttributeUpdate) SetUpdatedAt(v time.Time) *AttributeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *AttributeUpdate) SetAppID(v int) *AttributeUpdate {
	_u.mutation.ResetAppID()
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *AttributeUpdate) SetNillableAppID(v *int) *AttributeUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// AddAppID adds value to the "app_id" field.
func (_u *AttributeUpdate) AddAppID(v int) *AttributeUpdate {
	_u.mutation.AddAppID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AttributeUpdate) SetUserID(v int) *AttributeUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AttributeUpdate) SetNillableUserID(v *int) *AttributeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AttributeUpdate) AddUserID(v int) *AttributeUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AttributeUpdate) SetName(v string) *AttributeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AttributeUpdate) SetNillableName(v *string) *AttributeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AttributeUpdate) SetStatus(v int8) *AttributeUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AttributeUpdate) SetNillableStatus(v *int8) *AttributeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *AttributeUpdate) AddStatus(v int8) *AttributeUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// AddOptionIDs adds the "options" edge to the AttributeOption entity by IDs.
func (_u *AttributeUpdate) AddOptionIDs(ids ...int) *AttributeUpdate {
	_u.mutation.AddOptionIDs(ids...)
	return _u
}

// AddOptions adds the "options" edges to the AttributeOption entity.
func (_u *AttributeUpdate) AddOptions(v ...*AttributeOption) *AttributeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOptionIDs(ids...)
}

// AddProductAttributeIDs adds the "product_attributes" edge to the ProductAttribute entity by IDs.
func (_u *AttributeUpdate) AddProductAttributeIDs(ids ...int) *AttributeUpdate {
	_u.mutation.AddProductAttributeIDs(ids...)
	return _u
}

// AddProductAttributes adds the "product_attributes" edges to the ProductAttribute entity.
func (_u *AttributeUpdate) AddProductAttributes(v ...*ProductAttribute) *AttributeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProductAttributeIDs(ids...)
}

// Mutation returns the AttributeMutation object of the builder.
func (_u *AttributeUpdate) Mutation() *AttributeMutation {
	return _u.mutation
}

// ClearOptions clears all "options" edges to the AttributeOption entity.
func (_u *AttributeUpdate) ClearOptions() *AttributeUpdate {
	_u.mutation.ClearOptions()
	return _u
}

// RemoveOptionIDs removes the "options" edge to AttributeOption entities by IDs.
func (_u *AttributeUpdate) RemoveOptionIDs(ids ...int) *AttributeUpdate {
	_u.mutation.RemoveOptionIDs(ids...)
	return _u
}

// RemoveOptions removes "options" edges to AttributeOption entities.
func (_u *AttributeUpdate) RemoveOptions(v ...*AttributeOption) *AttributeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOptionIDs(ids...)
}

// ClearProductAttributes clears all "product_attributes" edges to the ProductAttribute entity.
func (_u *AttributeUpdate) ClearProductAttributes() *AttributeUpdate {
	_u.mutation.ClearProductAttributes()
	return _u
}

// RemoveProductAttributeIDs removes the "product_attributes" edge to ProductAttribute entities by IDs.
func (_u *AttributeUpdate) RemoveProductAttributeIDs(ids ...int) *AttributeUpdate {
	_u.mutation.RemoveProductAttributeIDs(ids...)
	return _u
}

// RemoveProductAttributes removes "product_attributes" edges to ProductAttribute entities.
func (_u *AttributeUpdate) RemoveProductAttributes(v ...*ProductAttribute) *AttributeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProductAttributeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AttributeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttributeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AttributeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttributeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AttributeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := attribute.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AttributeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := attribute.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Attribute.name": %w`, err)}
		}
	}
	return nil
}

func (_u *AttributeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(attribute.Table, attribute.Columns, sqlgraph.NewFieldSpec(attribute.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(attribute.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(attribute.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAppID(); ok {
		_spec.AddField(attribute.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(attribute.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(attribute.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(attribute.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(attribute.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(attribute.FieldStatus, field.TypeInt8, value)
	}
	if _u.mutation.OptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attribute.OptionsTable,
			Columns: []string{attribute.OptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attributeoption.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOptionsIDs(); len(nodes) > 0 && !_u.mutation.OptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attribute.OptionsTable,
			Columns: []string{attribute.OptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attributeoption.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attribute.OptionsTable,
			Columns: []string{attribute.OptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attributeoption.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductAttributesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attribute.ProductAttributesTable,
			Columns: []string{attribute.ProductAttributesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productattribute.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProductAttributesIDs(); len(nodes) > 0 && !_u.mutation.ProductAttributesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attribute.ProductAttributesTable,
			Columns: []string{attribute.ProductAttributesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productattribute.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductAttributesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attribute.ProductAttributesTable,
			Columns: []string{attribute.ProductAttributesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productattribute.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attribute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AttributeUpdateOne is the builder for updating a single Attribute entity.
type AttributeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AttributeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AttributeUpdateOne) SetUpdatedAt(v time.Time) *AttributeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *AttributeUpdateOne) SetAppID(v int) *AttributeUpdateOne {
	_u.mutation.ResetAppID()
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *AttributeUpdateOne) SetNillableAppID(v *int) *AttributeUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// AddAppID adds value to the "app_id" field.
func (_u *AttributeUpdateOne) AddAppID(v int) *AttributeUpdateOne {
	_u.mutation.AddAppID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AttributeUpdateOne) SetUserID(v int) *AttributeUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AttributeUpdateOne) SetNillableUserID(v *int) *AttributeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AttributeUpdateOne) AddUserID(v int) *AttributeUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AttributeUpdateOne) SetName(v string) *AttributeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AttributeUpdateOne) SetNillableName(v *string) *AttributeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AttributeUpdateOne) SetStatus(v int8) *AttributeUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AttributeUpdateOne) SetNillableStatus(v *int8) *AttributeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *AttributeUpdateOne) AddStatus(v int8) *AttributeUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// AddOptionIDs adds the "options" edge to the AttributeOption entity by IDs.
func (_u *AttributeUpdateOne) AddOptionIDs(ids ...int) *AttributeUpdateOne {
	_u.mutation.AddOptionIDs(ids...)
	return _u
}

// AddOptions adds the "options" edges to the AttributeOption entity.
func (_u *AttributeUpdateOne) AddOptions(v ...*AttributeOption) *AttributeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOptionIDs(ids...)
}

// AddProductAttributeIDs adds the "product_attributes" edge to the ProductAttribute entity by IDs.
func (_u *AttributeUpdateOne) AddProductAttributeIDs(ids ...int) *AttributeUpdateOne {
	_u.mutation.AddProductAttributeIDs(ids...)
	return _u
}

// AddProductAttributes adds the "product_attributes" edges to the ProductAttribute entity.
func (_u *AttributeUpdateOne) AddProductAttributes(v ...*ProductAttribute) *AttributeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProductAttributeIDs(ids...)
}

// Mutation returns the AttributeMutation object of the builder.
func (_u *AttributeUpdateOne) Mutation() *AttributeMutation {
	return _u.mutation
}

// ClearOptions clears all "options" edges to the AttributeOption entity.
func (_u *AttributeUpdateOne) ClearOptions() *AttributeUpdateOne {
	_u.mutation.ClearOptions()
	return _u
}

// RemoveOptionIDs removes the "options" edge to AttributeOption entities by IDs.
func (_u *AttributeUpdateOne) RemoveOptionIDs(ids ...int) *AttributeUpdateOne {
	_u.mutation.RemoveOptionIDs(ids...)
	return _u
}

// RemoveOptions removes "options" edges to AttributeOption entities.
func (_u *AttributeUpdateOne) RemoveOptions(v ...*AttributeOption) *AttributeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOptionIDs(ids...)
}

// ClearProductAttributes clears all "product_attributes" edges to the ProductAttribute entity.
func (_u *AttributeUpdateOne) ClearProductAttributes() *AttributeUpdateOne {
	_u.mutation.ClearProductAttributes()
	return _u
}

// RemoveProductAttributeIDs removes the "product_attributes" edge to ProductAttribute entities by IDs.
func (_u *AttributeUpdateOne) RemoveProductAttributeIDs(ids ...int) *AttributeUpdateOne {
	_u.mutation.RemoveProductAttributeIDs(ids...)
	return _u
}

// RemoveProductAttributes removes "product_attributes" edges to ProductAttribute entities.
func (_u *AttributeUpdateOne) RemoveProductAttributes(v ...*ProductAttribute) *AttributeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProductAttributeIDs(ids...)
}

// Where appends a list predicates to the AttributeUpdate builder.
func (_u *AttributeUpdateOne) Where(ps ...predicate.Attribute) *AttributeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AttributeUpdateOne) Select(field string, fields ...string) *AttributeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Attribute entity.
func (_u *AttributeUpdateOne) Save(ctx context.Context) (*Attribute, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttributeUpdateOne) SaveX(ctx context.Context) *Attribute {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AttributeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttributeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AttributeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := attribute.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AttributeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := attribute.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Attribute.name": %w`, err)}
		}
	}
	return nil
}

func (_u *AttributeUpdateOne) sqlSave(ctx context.Context) (_node *Attribute, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(attribute.Table, attribute.Columns, sqlgraph.NewFieldSpec(attribute.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Attribute.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attribute.FieldID)
		for _, f := range fields {
			if !attribute.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != attribute.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(attribute.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(attribute.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAppID(); ok {
		_spec.AddField(attribute.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(attribute.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(attribute.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(attribute.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(attribute.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(attribute.FieldStatus, field.TypeInt8, value)
	}
	if _u.mutation.OptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attribute.OptionsTable,
			Columns: []string{attribute.OptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attributeoption.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOptionsIDs(); len(nodes) > 0 && !_u.mutation.OptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attribute.OptionsTable,
			Columns: []string{attribute.OptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attributeoption.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attribute.OptionsTable,
			Columns: []string{attribute.OptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attributeoption.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductAttributesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attribute.ProductAttributesTable,
			Columns: []string{attribute.ProductAttributesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productattribute.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProductAttributesIDs(); len(nodes) > 0 && !_u.mutation.ProductAttributesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attribute.ProductAttributesTable,
			Columns: []string{attribute.ProductAttributesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productattribute.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductAttributesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   attribute.ProductAttributesTable,
			Columns: []string{attribute.ProductAttributesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productattribute.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Attribute{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attribute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
