// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ant/ent/order"
	"ant/ent/ordergroup"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderGroupCreate is the builder for creating a OrderGroup entity.
type OrderGroupCreate struct {
	config
	mutation *OrderGroupMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrderGroupCreate) SetCreatedAt(v time.Time) *OrderGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrderGroupCreate) SetNillableCreatedAt(v *time.Time) *OrderGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrderGroupCreate) SetUpdatedAt(v time.Time) *OrderGroupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrderGroupCreate) SetNillableUpdatedAt(v *time.Time) *OrderGroupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAppID sets the "app_id" field.
func (_c *OrderGroupCreate) SetAppID(v int) *OrderGroupCreate {
	_c.mutation.SetAppID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OrderGroupCreate) SetUserID(v int) *OrderGroupCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetDivisionID sets the "division_id" field.
func (_c *OrderGroupCreate) SetDivisionID(v int) *OrderGroupCreate {
	_c.mutation.SetDivisionID(v)
	return _c
}

// SetToken sets the "token" field.
func (_c *OrderGroupCreate) SetToken(v string) *OrderGroupCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetLabel sets the "label" field.
func (_c *OrderGroupCreate) SetLabel(v string) *OrderGroupCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *OrderGroupCreate) SetNillableLabel(v *string) *OrderGroupCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OrderGroupCreate) SetStatus(v int8) *OrderGroupCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OrderGroupCreate) SetNillableStatus(v *int8) *OrderGroupCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// AddOrderIDs adds the "orders" edge to the Order entity by IDs.
func (_c *OrderGroupCreate) AddOrderIDs(ids ...int) *OrderGroupCreate {
	_c.mutation.AddOrderIDs(ids...)
	return _c
}

// AddOrders adds the "orders" edges to the Order entity.
func (_c *OrderGroupCreate) AddOrders(v ...*Order) *OrderGroupCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOrderIDs(ids...)
}

// Mutation returns the OrderGroupMutation object of the builder.
func (_c *OrderGroupCreate) Mutation() *OrderGroupMutation {
	return _c.mutation
}

// Save creates the OrderGroup in the database.
func (_c *OrderGroupCreate) Save(ctx context.Context) (*OrderGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrderGroupCreate) SaveX(ctx context.Context) *OrderGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrderGroupCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ordergroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ordergroup.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := ordergroup.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrderGroupCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OrderGroup.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OrderGroup.updated_at"`)}
	}
	if _, ok := _c.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "OrderGroup.app_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OrderGroup.user_id"`)}
	}
	if _, ok := _c.mutation.DivisionID(); !ok {
		return &ValidationError{Name: "division_id", err: errors.New(`ent: missing required field "OrderGroup.division_id"`)}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "OrderGroup.token"`)}
	}
	if v, ok := _c.mutation.Token(); ok {
		if err := ordergroup.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "OrderGroup.token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OrderGroup.status"`)}
	}
	return nil
}

func (_c *OrderGroupCreate) sqlSave(ctx context.Context) (*OrderGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrderGroupCreate) createSpec() (*OrderGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &OrderGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ordergroup.Table, sqlgraph.NewFieldSpec(ordergroup.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ordergroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ordergroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AppID(); ok {
		_spec.SetField(ordergroup.FieldAppID, field.TypeInt, value)
		_node.AppID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(ordergroup.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.DivisionID(); ok {
		_spec.SetField(ordergroup.FieldDivisionID, field.TypeInt, value)
		_node.DivisionID = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(ordergroup.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(ordergroup.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(ordergroup.FieldStatus, field.TypeInt8, value)
		_node.Status = value
	}
	if nodes := _c.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ordergroup.OrdersTable,
			Columns: []string{ordergroup.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrderGroupCreateBulk is the builder for creating many OrderGroup entities in bulk.
type OrderGroupCreateBulk struct {
	config
	err      error
	builders []*OrderGroupCreate
}

// Save creates the OrderGroup entities in the database.
func (_c *OrderGroupCreateBulk) Save(ctx context.Context) ([]*OrderGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OrderGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrderGroupCreateBulk) SaveX(ctx context.Context) []*OrderGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
