// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ant/ent/order"
	"ant/ent/ordergroup"
	"ant/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderGroupUpdate is the builder for updating OrderGroup entities.
type OrderGroupUpdate struct {
	config
	hooks    []Hook
	mutation *OrderGroupMutation
}

// Where appends a list predicates to the OrderGroupUpdate builder.
func (_u *OrderGroupUpdate) Where(ps ...predicate.OrderGroup) *OrderGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderGroupUpdate) SetUpdatedAt(v time.Time) *OrderGroupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *OrderGroupUpdate) SetAppID(v int) *OrderGroupUpdate {
	_u.mutation.ResetAppID()
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *OrderGroupUpdate) SetNillableAppID(v *int) *OrderGroupUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// AddAppID adds value to the "app_id" field.
func (_u *OrderGroupUpdate) AddAppID(v int) *OrderGroupUpdate {
	_u.mutation.AddAppID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrderGroupUpdate) SetUserID(v int) *OrderGroupUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrderGroupUpdate) SetNillableUserID(v *int) *OrderGroupUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OrderGroupUpdate) AddUserID(v int) *OrderGroupUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetDivisionID sets the "division_id" field.
func (_u *OrderGroupUpdate) SetDivisionID(v int) *OrderGroupUpdate {
	_u.mutation.ResetDivisionID()
	_u.mutation.SetDivisionID(v)
	return _u
}

// SetNillableDivisionID sets the "division_id" field if the given value is not nil.
func (_u *OrderGroupUpdate) SetNillableDivisionID(v *int) *OrderGroupUpdate {
	if v != nil {
		_u.SetDivisionID(*v)
	}
	return _u
}

// AddDivisionID adds value to the "division_id" field.
func (_u *OrderGroupUpdate) AddDivisionID(v int) *OrderGroupUpdate {
	_u.mutation.AddDivisionID(v)
	return _u
}

// SetToken sets the "token" field.
func (_u *OrderGroupUpdate) SetToken(v string) *OrderGroupUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *OrderGroupUpdate) SetNillableToken(v *string) *OrderGroupUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *OrderGroupUpdate) SetLabel(v string) *OrderGroupUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *OrderGroupUpdate) SetNillableLabel(v *string) *OrderGroupUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *OrderGroupUpdate) ClearLabel() *OrderGroupUpdate {
	_u.mutation.ClearLabel()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderGroupUpdate) SetStatus(v int8) *OrderGroupUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderGroupUpdate) SetNillableStatus(v *int8) *OrderGroupUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *OrderGroupUpdate) AddStatus(v int8) *OrderGroupUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// AddOrderIDs adds the "orders" edge to the Order entity by IDs.
func (_u *OrderGroupUpdate) AddOrderIDs(ids ...int) *OrderGroupUpdate {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the Order entity.
func (_u *OrderGroupUpdate) AddOrders(v ...*Order) *OrderGroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// Mutation returns the OrderGroupMutation object of the builder.
func (_u *OrderGroupUpdate) Mutation() *OrderGroupMutation {
	return _u.mutation
}

// ClearOrders clears all "orders" edges to the Order entity.
func (_u *OrderGroupUpdate) ClearOrders() *OrderGroupUpdate {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to Order entities by IDs.
func (_u *OrderGroupUpdate) RemoveOrderIDs(ids ...int) *OrderGroupUpdate {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to Order entities.
func (_u *OrderGroupUpdate) RemoveOrders(v ...*Order) *OrderGroupUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderGroupUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderGroupUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ordergroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderGroupUpdate) check() error {
	if v, ok := _u.mutation.Token(); ok {
		if err := ordergroup.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "OrderGroup.token": %w`, err)}
		}
	}
	return nil
}

func (_u *OrderGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ordergroup.Table, ordergroup.Columns, sqlgraph.NewFieldSpec(ordergroup.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ordergroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(ordergroup.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAppID(); ok {
		_spec.AddField(ordergroup.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(ordergroup.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(ordergroup.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DivisionID(); ok {
		_spec.SetField(ordergroup.FieldDivisionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDivisionID(); ok {
		_spec.AddField(ordergroup.FieldDivisionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(ordergroup.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(ordergroup.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(ordergroup.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ordergroup.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(ordergroup.FieldStatus, field.TypeInt8, value)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ordergroup.OrdersTable,
			Columns: []string{ordergroup.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ordergroup.OrdersTable,
			Columns: []string{ordergroup.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ordergroup.OrdersTable,
			Columns: []string{ordergroup.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ordergroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderGroupUpdateOne is the builder for updating a single OrderGroup entity.
type OrderGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderGroupMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderGroupUpdateOne) SetUpdatedAt(v time.Time) *OrderGroupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *OrderGroupUpdateOne) SetAppID(v int) *OrderGroupUpdateOne {
	_u.mutation.ResetAppID()
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *OrderGroupUpdateOne) SetNillableAppID(v *int) *OrderGroupUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// AddAppID adds value to the "app_id" field.
func (_u *OrderGroupUpdateOne) AddAppID(v int) *OrderGroupUpdateOne {
	_u.mutation.AddAppID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrderGroupUpdateOne) SetUserID(v int) *OrderGroupUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrderGroupUpdateOne) SetNillableUserID(v *int) *OrderGroupUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *OrderGroupUpdateOne) AddUserID(v int) *OrderGroupUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetDivisionID sets the "division_id" field.
func (_u *OrderGroupUpdateOne) SetDivisionID(v int) *OrderGroupUpdateOne {
	_u.mutation.ResetDivisionID()
	_u.mutation.SetDivisionID(v)
	return _u
}

// SetNillableDivisionID sets the "division_id" field if the given value is not nil.
func (_u *OrderGroupUpdateOne) SetNillableDivisionID(v *int) *OrderGroupUpdateOne {
	if v != nil {
		_u.SetDivisionID(*v)
	}
	return _u
}

// AddDivisionID adds value to the "division_id" field.
func (_u *OrderGroupUpdateOne) AddDivisionID(v int) *OrderGroupUpdateOne {
	_u.mutation.AddDivisionID(v)
	return _u
}

// SetToken sets the "token" field.
func (_u *OrderGroupUpdateOne) SetToken(v string) *OrderGroupUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *OrderGroupUpdateOne) SetNillableToken(v *string) *OrderGroupUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *OrderGroupUpdateOne) SetLabel(v string) *OrderGroupUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *OrderGroupUpdateOne) SetNillableLabel(v *string) *OrderGroupUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *OrderGroupUpdateOne) ClearLabel() *OrderGroupUpdateOne {
	_u.mutation.ClearLabel()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderGroupUpdateOne) SetStatus(v int8) *OrderGroupUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderGroupUpdateOne) SetNillableStatus(v *int8) *OrderGroupUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *OrderGroupUpdateOne) AddStatus(v int8) *OrderGroupUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// AddOrderIDs adds the "orders" edge to the Order entity by IDs.
func (_u *OrderGroupUpdateOne) AddOrderIDs(ids ...int) *OrderGroupUpdateOne {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the Order entity.
func (_u *OrderGroupUpdateOne) AddOrders(v ...*Order) *OrderGroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// Mutation returns the OrderGroupMutation object of the builder.
func (_u *OrderGroupUpdateOne) Mutation() *OrderGroupMutation {
	return _u.mutation
}

// ClearOrders clears all "orders" edges to the Order entity.
func (_u *OrderGroupUpdateOne) ClearOrders() *OrderGroupUpdateOne {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to Order entities by IDs.
func (_u *OrderGroupUpdateOne) RemoveOrderIDs(ids ...int) *OrderGroupUpdateOne {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to Order entities.
func (_u *OrderGroupUpdateOne) RemoveOrders(v ...*Order) *OrderGroupUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// Where appends a list predicates to the OrderGroupUpdate builder.
func (_u *OrderGroupUpdateOne) Where(ps ...predicate.OrderGroup) *OrderGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderGroupUpdateOne) Select(field string, fields ...string) *OrderGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrderGroup entity.
func (_u *OrderGroupUpdateOne) Save(ctx context.Context) (*OrderGroup, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderGroupUpdateOne) SaveX(ctx context.Context) *OrderGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderGroupUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ordergroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderGroupUpdateOne) check() error {
	if v, ok := _u.mutation.Token(); ok {
		if err := ordergroup.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "OrderGroup.token": %w`, err)}
		}
	}
	return nil
}

func (_u *OrderGroupUpdateOne) sqlSave(ctx context.Context) (_node *OrderGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ordergroup.Table, ordergroup.Columns, sqlgraph.NewFieldSpec(ordergroup.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrderGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ordergroup.FieldID)
		for _, f := range fields {
			if !ordergroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ordergroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ordergroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(ordergroup.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAppID(); ok {
		_spec.AddField(ordergroup.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(ordergroup.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(ordergroup.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DivisionID(); ok {
		_spec.SetField(ordergroup.FieldDivisionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDivisionID(); ok {
		_spec.AddField(ordergroup.FieldDivisionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(ordergroup.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(ordergroup.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(ordergroup.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ordergroup.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(ordergroup.FieldStatus, field.TypeInt8, value)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ordergroup.OrdersTable,
			Columns: []string{ordergroup.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ordergroup.OrdersTable,
			Columns: []string{ordergroup.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ordergroup.OrdersTable,
			Columns: []string{ordergroup.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrderGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ordergroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
