// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ant/ent/attribute"
	"ant/ent/product"
	"ant/ent/productattribute"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ProductAttribute is the model entity for the ProductAttribute schema.
type ProductAttribute struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID int `json:"product_id,omitempty"`
	// AttributeID holds the value of the "attribute_id" field.
	AttributeID int `json:"attribute_id,omitempty"`
	// IsMandatory holds the value of the "is_mandatory" field.
	IsMandatory bool `json:"is_mandatory,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProductAttributeQuery when eager-loading is set.
	Edges        ProductAttributeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProductAttributeEdges holds the relations/edges for other nodes in the graph.
type ProductAttributeEdges struct {
	// Product holds the value of the product edge.
	Product *Product `json:"product,omitempty"`
	// Attribute holds the value of the attribute edge.
	Attribute *Attribute `json:"attribute,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProductAttributeEdges) ProductOrErr() (*Product, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: product.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// AttributeOrErr returns the Attribute value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProductAttributeEdges) AttributeOrErr() (*Attribute, error) {
	if e.Attribute != nil {
		return e.Attribute, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: attribute.Label}
	}
	return nil, &NotLoadedError{edge: "attribute"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProductAttribute) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case productattribute.FieldIsMandatory:
			values[i] = new(sql.NullBool)
		case productattribute.FieldID, productattribute.FieldProductID, productattribute.FieldAttributeID:
			values[i] = new(sql.NullInt64)
		case productattribute.FieldCreatedAt, productattribute.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProductAttribute fields.
func (_m *ProductAttribute) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case productattribute.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case productattribute.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case productattribute.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case productattribute.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				_m.ProductID = int(value.Int64)
			}
		case productattribute.FieldAttributeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attribute_id", values[i])
			} else if value.Valid {
				_m.AttributeID = int(value.Int64)
			}
		case productattribute.FieldIsMandatory:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_mandatory", values[i])
			} else if value.Valid {
				_m.IsMandatory = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProductAttribute.
// This includes values selected through modifiers, order, etc.
func (_m *ProductAttribute) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProduct queries the "product" edge of the ProductAttribute entity.
func (_m *ProductAttribute) QueryProduct() *ProductQuery {
	return NewProductAttributeClient(_m.config).QueryProduct(_m)
}

// QueryAttribute queries the "attribute" edge of the ProductAttribute entity.
func (_m *ProductAttribute) QueryAttribute() *AttributeQuery {
	return NewProductAttributeClient(_m.config).QueryAttribute(_m)
}

// Update returns a builder for updating this ProductAttribute.
// Note that you need to call ProductAttribute.Unwrap() before calling this method if this ProductAttribute
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProductAttribute) Update() *ProductAttributeUpdateOne {
	return NewProductAttributeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProductAttribute entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProductAttribute) Unwrap() *ProductAttribute {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProductAttribute is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProductAttribute) String() string {
	var builder strings.Builder
	builder.WriteString("ProductAttribute(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductID))
	builder.WriteString(", ")
	builder.WriteString("attribute_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttributeID))
	builder.WriteString(", ")
	builder.WriteString("is_mandatory=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsMandatory))
	builder.WriteByte(')')
	return builder.String()
}

// ProductAttributes is a parsable slice of ProductAttribute.
type ProductAttributes []*ProductAttribute
