// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ant/ent/attribute"
	"ant/ent/attributeoption"
	"ant/ent/category"
	"ant/ent/order"
	"ant/ent/ordergroup"
	"ant/ent/orderproduct"
	"ant/ent/product"
	"ant/ent/productattribute"
	"ant/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attributeMixin := schema.Attribute{}.Mixin()
	attributeMixinFields0 := attributeMixin[0].Fields()
	_ = attributeMixinFields0
	attributeFields := schema.Attribute{}.Fields()
	_ = attributeFields
	// attributeDescCreatedAt is the schema descriptor for created_at field.
	attributeDescCreatedAt := attributeMixinFields0[0].Descriptor()
	// attribute.DefaultCreatedAt holds the default value on creation for the created_at field.
	attribute.DefaultCreatedAt = attributeDescCreatedAt.Default.(func() time.Time)
	// attributeDescUpdatedAt is the schema descriptor for updated_at field.
	attributeDescUpdatedAt := attributeMixinFields0[1].Descriptor()
	// attribute.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	attribute.DefaultUpdatedAt = attributeDescUpdatedAt.Default.(func() time.Time)
	// attribute.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	attribute.UpdateDefaultUpdatedAt = attributeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// attributeDescName is the schema descriptor for name field.
	attributeDescName := attributeFields[3].Descriptor()
	// attribute.NameValidator is a validator for the "name" field. It is called by the builders before save.
	attribute.NameValidator = attributeDescName.Validators[0].(func(string) error)
	// attributeDescStatus is the schema descriptor for status field.
	attributeDescStatus := attributeFields[4].Descriptor()
	// attribute.DefaultStatus holds the default value on creation for the status field.
	attribute.DefaultStatus = attributeDescStatus.Default.(int8)
	attributeoptionMixin := schema.AttributeOption{}.Mixin()
	attributeoptionMixinFields0 := attributeoptionMixin[0].Fields()
	_ = attributeoptionMixinFields0
	attributeoptionFields := schema.AttributeOption{}.Fields()
	_ = attributeoptionFields
	// attributeoptionDescCreatedAt is the schema descriptor for created_at field.
	attributeoptionDescCreatedAt := attributeoptionMixinFields0[0].Descriptor()
	// attributeoption.DefaultCreatedAt holds the default value on creation for the created_at field.
	attributeoption.DefaultCreatedAt = attributeoptionDescCreatedAt.Default.(func() time.Time)
	// attributeoptionDescUpdatedAt is the schema descriptor for updated_at field.
	attributeoptionDescUpdatedAt := attributeoptionMixinFields0[1].Descriptor()
	// attributeoption.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	attributeoption.DefaultUpdatedAt = attributeoptionDescUpdatedAt.Default.(func() time.Time)
	// attributeoption.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	attributeoption.UpdateDefaultUpdatedAt = attributeoptionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// attributeoptionDescValue is the schema descriptor for value field.
	attributeoptionDescValue := attributeoptionFields[1].Descriptor()
	// attributeoption.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	attributeoption.ValueValidator = attributeoptionDescValue.Validators[0].(func(string) error)
	categoryMixin := schema.Category{}.Mixin()
	categoryMixinFields0 := categoryMixin[0].Fields()
	_ = categoryMixinFields0
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryMixinFields0[0].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdatedAt is the schema descriptor for updated_at field.
	categoryDescUpdatedAt := categoryMixinFields0[1].Descriptor()
	// category.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	category.DefaultUpdatedAt = categoryDescUpdatedAt.Default.(func() time.Time)
	// category.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	category.UpdateDefaultUpdatedAt = categoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// categoryDescName is the schema descriptor for name field.
	categoryDescName := categoryFields[3].Descriptor()
	// category.NameValidator is a validator for the "name" field. It is called by the builders before save.
	category.NameValidator = categoryDescName.Validators[0].(func(string) error)
	// categoryDescDepth is the schema descriptor for depth field.
	categoryDescDepth := categoryFields[5].Descriptor()
	// category.DefaultDepth holds the default value on creation for the depth field.
	category.DefaultDepth = categoryDescDepth.Default.(int8)
	// categoryDescStatus is the schema descriptor for status field.
	categoryDescStatus := categoryFields[6].Descriptor()
	// category.DefaultStatus holds the default value on creation for the status field.
	category.DefaultStatus = categoryDescStatus.Default.(int8)
	orderMixin := schema.Order{}.Mixin()
	orderMixinFields0 := orderMixin[0].Fields()
	_ = orderMixinFields0
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderMixinFields0[0].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	// orderDescUpdatedAt is the schema descriptor for updated_at field.
	orderDescUpdatedAt := orderMixinFields0[1].Descriptor()
	// order.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	order.DefaultUpdatedAt = orderDescUpdatedAt.Default.(func() time.Time)
	// order.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	order.UpdateDefaultUpdatedAt = orderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderDescCustomerName is the schema descriptor for customer_name field.
	orderDescCustomerName := orderFields[4].Descriptor()
	// order.CustomerNameValidator is a validator for the "customer_name" field. It is called by the builders before save.
	order.CustomerNameValidator = orderDescCustomerName.Validators[0].(func(string) error)
	// orderDescCustomerContact is the schema descriptor for customer_contact field.
	orderDescCustomerContact := orderFields[5].Descriptor()
	// order.CustomerContactValidator is a validator for the "customer_contact" field. It is called by the builders before save.
	order.CustomerContactValidator = orderDescCustomerContact.Validators[0].(func(string) error)
	// orderDescOrderedAt is the schema descriptor for ordered_at field.
	orderDescOrderedAt := orderFields[6].Descriptor()
	// order.DefaultOrderedAt holds the default value on creation for the ordered_at field.
	order.DefaultOrderedAt = orderDescOrderedAt.Default.(func() time.Time)
	// orderDescStatus is the schema descriptor for status field.
	orderDescStatus := orderFields[7].Descriptor()
	// order.DefaultStatus holds the default value on creation for the status field.
	order.DefaultStatus = orderDescStatus.Default.(int8)
	// orderDescTaxPercent is the schema descriptor for tax_percent field.
	orderDescTaxPercent := orderFields[8].Descriptor()
	// order.DefaultTaxPercent holds the default value on creation for the tax_percent field.
	order.DefaultTaxPercent = orderDescTaxPercent.Default.(float64)
	// order.TaxPercentValidator is a validator for the "tax_percent" field. It is called by the builders before save.
	order.TaxPercentValidator = func() func(float64) error {
		validators := orderDescTaxPercent.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(tax_percent float64) error {
			for _, fn := range fns {
				if err := fn(tax_percent); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// orderDescTotal is the schema descriptor for total field.
	orderDescTotal := orderFields[9].Descriptor()
	// order.DefaultTotal holds the default value on creation for the total field.
	order.DefaultTotal = orderDescTotal.Default.(float64)
	// order.TotalValidator is a validator for the "total" field. It is called by the builders before save.
	order.TotalValidator = orderDescTotal.Validators[0].(func(float64) error)
	// orderDescIPAddress is the schema descriptor for ip_address field.
	orderDescIPAddress := orderFields[10].Descriptor()
	// order.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	order.IPAddressValidator = orderDescIPAddress.Validators[0].(func(string) error)
	// orderDescDeviceID is the schema descriptor for device_id field.
	orderDescDeviceID := orderFields[11].Descriptor()
	// order.DeviceIDValidator is a validator for the "device_id" field. It is called by the builders before save.
	order.DeviceIDValidator = orderDescDeviceID.Validators[0].(func(string) error)
	ordergroupMixin := schema.OrderGroup{}.Mixin()
	ordergroupMixinFields0 := ordergroupMixin[0].Fields()
	_ = ordergroupMixinFields0
	ordergroupFields := schema.OrderGroup{}.Fields()
	_ = ordergroupFields
	// ordergroupDescCreatedAt is the schema descriptor for created_at field.
	ordergroupDescCreatedAt := ordergroupMixinFields0[0].Descriptor()
	// ordergroup.DefaultCreatedAt holds the default value on creation for the created_at field.
	ordergroup.DefaultCreatedAt = ordergroupDescCreatedAt.Default.(func() time.Time)
	// ordergroupDescUpdatedAt is the schema descriptor for updated_at field.
	ordergroupDescUpdatedAt := ordergroupMixinFields0[1].Descriptor()
	// ordergroup.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ordergroup.DefaultUpdatedAt = ordergroupDescUpdatedAt.Default.(func() time.Time)
	// ordergroup.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ordergroup.UpdateDefaultUpdatedAt = ordergroupDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ordergroupDescToken is the schema descriptor for token field.
	ordergroupDescToken := ordergroupFields[3].Descriptor()
	// ordergroup.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	ordergroup.TokenValidator = ordergroupDescToken.Validators[0].(func(string) error)
	// ordergroupDescStatus is the schema descriptor for status field.
	ordergroupDescStatus := ordergroupFields[5].Descriptor()
	// ordergroup.DefaultStatus holds the default value on creation for the status field.
	ordergroup.DefaultStatus = ordergroupDescStatus.Default.(int8)
	orderproductMixin := schema.OrderProduct{}.Mixin()
	orderproductMixinFields0 := orderproductMixin[0].Fields()
	_ = orderproductMixinFields0
	orderproductFields := schema.OrderProduct{}.Fields()
	_ = orderproductFields
	// orderproductDescCreatedAt is the schema descriptor for created_at field.
	orderproductDescCreatedAt := orderproductMixinFields0[0].Descriptor()
	// orderproduct.DefaultCreatedAt holds the default value on creation for the created_at field.
	orderproduct.DefaultCreatedAt = orderproductDescCreatedAt.Default.(func() time.Time)
	// orderproductDescUpdatedAt is the schema descriptor for updated_at field.
	orderproductDescUpdatedAt := orderproductMixinFields0[1].Descriptor()
	// orderproduct.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	orderproduct.DefaultUpdatedAt = orderproductDescUpdatedAt.Default.(func() time.Time)
	// orderproduct.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	orderproduct.UpdateDefaultUpdatedAt = orderproductDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderproductDescProductName is the schema descriptor for product_name field.
	orderproductDescProductName := orderproductFields[2].Descriptor()
	// orderproduct.ProductNameValidator is a validator for the "product_name" field. It is called by the builders before save.
	orderproduct.ProductNameValidator = orderproductDescProductName.Validators[0].(func(string) error)
	// orderproductDescQuantity is the schema descriptor for quantity field.
	orderproductDescQuantity := orderproductFields[4].Descriptor()
	// orderproduct.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	orderproduct.QuantityValidator = orderproductDescQuantity.Validators[0].(func(int) error)
	// orderproductDescAttributes is the schema descriptor for attributes field.
	orderproductDescAttributes := orderproductFields[5].Descriptor()
	// orderproduct.DefaultAttributes holds the default value on creation for the attributes field.
	orderproduct.DefaultAttributes = orderproductDescAttributes.Default.([]schema.OrderItemAttribute)
	productMixin := schema.Product{}.Mixin()
	productMixinFields0 := productMixin[0].Fields()
	_ = productMixinFields0
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescCreatedAt is the schema descriptor for created_at field.
	productDescCreatedAt := productMixinFields0[0].Descriptor()
	// product.DefaultCreatedAt holds the default value on creation for the created_at field.
	product.DefaultCreatedAt = productDescCreatedAt.Default.(func() time.Time)
	// productDescUpdatedAt is the schema descriptor for updated_at field.
	productDescUpdatedAt := productMixinFields0[1].Descriptor()
	// product.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	product.DefaultUpdatedAt = productDescUpdatedAt.Default.(func() time.Time)
	// product.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	product.UpdateDefaultUpdatedAt = productDescUpdatedAt.UpdateDefault.(func() time.Time)
	// productDescName is the schema descriptor for name field.
	productDescName := productFields[3].Descriptor()
	// product.NameValidator is a validator for the "name" field. It is called by the builders before save.
	product.NameValidator = productDescName.Validators[0].(func(string) error)
	// productDescPrice is the schema descriptor for price field.
	productDescPrice := productFields[4].Descriptor()
	// product.DefaultPrice holds the default value on creation for the price field.
	product.DefaultPrice = productDescPrice.Default.(float64)
	// productDescStatus is the schema descriptor for status field.
	productDescStatus := productFields[5].Descriptor()
	// product.DefaultStatus holds the default value on creation for the status field.
	product.DefaultStatus = productDescStatus.Default.(int8)
	productattributeMixin := schema.ProductAttribute{}.Mixin()
	productattributeMixinFields0 := productattributeMixin[0].Fields()
	_ = productattributeMixinFields0
	productattributeFields := schema.ProductAttribute{}.Fields()
	_ = productattributeFields
	// productattributeDescCreatedAt is the schema descriptor for created_at field.
	productattributeDescCreatedAt := productattributeMixinFields0[0].Descriptor()
	// productattribute.DefaultCreatedAt holds the default value on creation for the created_at field.
	productattribute.DefaultCreatedAt = productattributeDescCreatedAt.Default.(func() time.Time)
	// productattributeDescUpdatedAt is the schema descriptor for updated_at field.
	productattributeDescUpdatedAt := productattributeMixinFields0[1].Descriptor()
	// productattribute.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	productattribute.DefaultUpdatedAt = productattributeDescUpdatedAt.Default.(func() time.Time)
	// productattribute.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	productattribute.UpdateDefaultUpdatedAt = productattributeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// productattributeDescIsMandatory is the schema descriptor for is_mandatory field.
	productattributeDescIsMandatory := productattributeFields[2].Descriptor()
	// productattribute.DefaultIsMandatory holds the default value on creation for the is_mandatory field.
	productattribute.DefaultIsMandatory = productattributeDescIsMandatory.Default.(bool)
	// productattributeDescOptions is the schema descriptor for options field.
	productattributeDescOptions := productattributeFields[3].Descriptor()
	// productattribute.DefaultOptions holds the default value on creation for the options field.
	productattribute.DefaultOptions = productattributeDescOptions.Default.([]schema.ProductAttributeOption)
}
