// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ant/ent/predicate"
	"ant/ent/storefront"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StorefrontDelete is the builder for deleting a Storefront entity.
type StorefrontDelete struct {
	config
	hooks    []Hook
	mutation *StorefrontMutation
}

// Where appends a list predicates to the StorefrontDelete builder.
func (_d *StorefrontDelete) Where(ps ...predicate.Storefront) *StorefrontDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *StorefrontDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StorefrontDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *StorefrontDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(storefront.Table, sqlgraph.NewFieldSpec(storefront.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// StorefrontDeleteOne is the builder for deleting a single Storefront entity.
type StorefrontDeleteOne struct {
	_d *StorefrontDelete
}

// Where appends a list predicates to the StorefrontDelete builder.
func (_d *StorefrontDeleteOne) Where(ps ...predicate.Storefront) *StorefrontDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *StorefrontDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{storefront.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StorefrontDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
