// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ant/ent/schema"
	"ant/ent/storefront"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Storefront is the model entity for the Storefront schema.
type Storefront struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID int `json:"app_id,omitempty"`
	// DivisionID holds the value of the "division_id" field.
	DivisionID int `json:"division_id,omitempty"`
	// HeroImage holds the value of the "hero_image" field.
	HeroImage string `json:"hero_image,omitempty"`
	// Assessments holds the value of the "assessments" field.
	Assessments []schema.Assessment `json:"assessments,omitempty"`
	// Gallery holds the value of the "gallery" field.
	Gallery []schema.GalleryImage `json:"gallery,omitempty"`
	// FoodTags holds the value of the "food_tags" field.
	FoodTags []schema.FoodTag `json:"food_tags,omitempty"`
	// Status holds the value of the "status" field.
	Status       int8 `json:"status,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Storefront) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case storefront.FieldAssessments, storefront.FieldGallery, storefront.FieldFoodTags:
			values[i] = new([]byte)
		case storefront.FieldID, storefront.FieldAppID, storefront.FieldDivisionID, storefront.FieldStatus:
			values[i] = new(sql.NullInt64)
		case storefront.FieldHeroImage:
			values[i] = new(sql.NullString)
		case storefront.FieldCreatedAt, storefront.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Storefront fields.
func (_m *Storefront) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case storefront.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case storefront.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case storefront.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case storefront.FieldAppID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value.Valid {
				_m.AppID = int(value.Int64)
			}
		case storefront.FieldDivisionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field division_id", values[i])
			} else if value.Valid {
				_m.DivisionID = int(value.Int64)
			}
		case storefront.FieldHeroImage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hero_image", values[i])
			} else if value.Valid {
				_m.HeroImage = value.String
			}
		case storefront.FieldAssessments:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field assessments", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Assessments); err != nil {
					return fmt.Errorf("unmarshal field assessments: %w", err)
				}
			}
		case storefront.FieldGallery:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field gallery", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Gallery); err != nil {
					return fmt.Errorf("unmarshal field gallery: %w", err)
				}
			}
		case storefront.FieldFoodTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field food_tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.FoodTags); err != nil {
					return fmt.Errorf("unmarshal field food_tags: %w", err)
				}
			}
		case storefront.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int8(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Storefront.
// This includes values selected through modifiers, order, etc.
func (_m *Storefront) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Storefront.
// Note that you need to call Storefront.Unwrap() before calling this method if this Storefront
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Storefront) Update() *StorefrontUpdateOne {
	return NewStorefrontClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Storefront entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Storefront) Unwrap() *Storefront {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Storefront is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Storefront) String() string {
	var builder strings.Builder
	builder.WriteString("Storefront(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("app_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AppID))
	builder.WriteString(", ")
	builder.WriteString("division_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DivisionID))
	builder.WriteString(", ")
	builder.WriteString("hero_image=")
	builder.WriteString(_m.HeroImage)
	builder.WriteString(", ")
	builder.WriteString("assessments=")
	builder.WriteString(fmt.Sprintf("%v", _m.Assessments))
	builder.WriteString(", ")
	builder.WriteString("gallery=")
	builder.WriteString(fmt.Sprintf("%v", _m.Gallery))
	builder.WriteString(", ")
	builder.WriteString("food_tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.FoodTags))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteByte(')')
	return builder.String()
}

// Storefronts is a parsable slice of Storefront.
type Storefronts []*Storefront
