// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Attribute is the predicate function for attribute builders.
type Attribute func(*sql.Selector)

// AttributeOption is the predicate function for attributeoption builders.
type AttributeOption func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OrderGroup is the predicate function for ordergroup builders.
type OrderGroup func(*sql.Selector)

// OrderProduct is the predicate function for orderproduct builders.
type OrderProduct func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// ProductAttribute is the predicate function for productattribute builders.
type ProductAttribute func(*sql.Selector)
